### ISSUE TITLE
customize to display

### ISSUE THREAD

**Issue by Andryev** [Iris0905/angular-onscreen-material-keyboard#15]
How I customize to display or not some letters.

For example, I don't need Enter, how can I remove it from the layout?

**Comment by joshstrohminger** [comment]
See the main readme for [providing custom layouts](https://github.com/Iris0905/angular-onscreen-material-keyboard#providing-custom-layouts) which refers to [another comment from the original source code](https://goo.gl/fCDExr).

I'm not sure how it'll look to remove a key, but maybe you can find a way after reading through it and playing around.
