### ISSUE TITLE
 Directive MatKeyboardDirective, Expected 0 arguments, but got 1

### ISSUE THREAD

**Issue by ankitp5** [Iris0905/angular-onscreen-material-keyboard#18]
page.component.html(138,17): : Directive MatKeyboardDirective, Expected 0 arguments, but got 1.

i am facing the issue while creating --prod build.

i tired to remove all the @HostListener as per https://stackoverflow.com/a/50409526 
but it is not working 

system information is:
Ionic:

   Ionic CLI                     : 6.10.1
   Ionic Framework               : @ionic/angular 4.11.10
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.1
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v12.18.2 
   npm               : 6.14.5
   OS                : Windows 10

thanks...

**Comment by Andrewnames** [comment]
hey @ankitp5   ! Were you able to make it working ?

**Comment by ankitp5** [comment]
@Andrewnames nope i am using build without --prod only.

**Comment by Andrewnames** [comment]
my issue was @angular-devkit/build-angular : 0.803.29 was mismatching with installed angular version
